# -*- coding: utf-8 -*-
"""streamlitrr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrylnjkx9YnK9Wa7Jb6giO0aa1jIFz1n
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlitapp.py
# import streamlit as st
# import appdirs as ad
# ad.user_cache_dir= lambda *args: './tmp'
# st.title("jinsei wa jigoku!")
# st.title("1 one firm for artists and graphics")
# st.badge("hitori",color="red")




