# -*- coding: utf-8 -*-
"""streamlitrr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrylnjkx9YnK9Wa7Jb6giO0aa1jIFz1n
"""

!pip install streamlit appdirs

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlitapp.py
# import streamlit as st
# import appdirs as ad
# ad.user_cache_dir= lambda *args: './tmp'
# st.title("jinsei wa jigoku!")
# image_url="https://www.google.com/imgres?q=rick%20ashley&imgurl=https%3A%2F%2Fi.redd.it%2Ffsh2qi0yrbr71.png&imgrefurl=https%3A%2F%2Fwww.reddit.com%2Fr%2FBossfight%2Fcomments%2Fq0u5yf%2F%25F0%259D%2595%25BD%25F0%259D%2596%258E%25F0%259D%2596%2588%25F0%259D%2596%2590_%25F0%259D%2595%25AC%25F0%259D%2596%2598%25F0%259D%2596%258D%25F0%259D%2596%2591%25F0%259D%2596%258A%25F0%259D%2596%259E_%25F0%259D%2595%25B7%25F0%259D%2596%2594%25F0%259D%2596%2597%25F0%259D%2596%2589_%25F0%259D%2595%25BA%25F0%259D%2596%258B_%25F0%259D%2595%25AF%25F0%259D%2596%258E%25F0%259D%2596%2598%25F0%259D%2596%2586%25F0%259D%2596%2595%25F0%259D%2596%2595%25F0%259D%2596%2594%25F0%259D%2596%258E%25F0%259D%2596%2593%25F0%259D%2596%2599%25F0%259D%2596%2592%25F0%259D%2596%258A%25F0%259D%2596%2593%25F0%259D%2596%2599%2F&docid=YSnhGHzENrrLTM&tbnid=zIqWBdwEW3nc8M&vet=12ahUKEwjT6KGFxLmQAxUXdPUHHfXOKTIQM3oECB0QAA..i&w=1200&h=1200&hcb=2&ved=2ahUKEwjT6KGFxLmQAxUXdPUHHfXOKTIQM3oECB0QAA"
# st.image("image_url")
# st.title("1 one firm for artists and graphics")
# st.badge("hitori",color="red")
#

!npm install -g localtunnel

!curl ipv4.icanhazip.com

!streamlit run streamlitapp.py & >./logs.txt & npx localtunnel --port 8501 & curl ipv4.icanhazip.com

